export const VALIDATOR_STATUS = Object.freeze({
  PASS: "pass",
  PASS_WITH_WARNINGS: "pass_with_warnings",
  BLOCKED_SOURCE_REQUIRED: "blocked_source_required",
  BLOCKED_OBJECT_MISMATCH: "blocked_object_mismatch",
  BLOCKED_SCHEMA_ERROR: "blocked_schema_error",
  BLOCKED_POLICY_VIOLATION: "blocked_policy_violation",
  BLOCKED_GENERIC_FILLER: "blocked_generic_filler",
  BLOCKED_PAGE_CONTEXT_MISSING: "blocked_page_context_missing",
  BLOCKED_PAGE_CONTEXT_MISMATCH: "blocked_page_context_mismatch",
  BLOCKED_FRESHNESS_UNVERIFIED: "blocked_freshness_unverified",
  USER_INPUT_REQUIRED: "user_input_required",
  SOURCE_REQUIRED: "source_required",
  REALTIME_VERIFICATION_REQUIRED: "realtime_verification_required",
  PROVIDER_ERROR: "provider_error",
  PROVIDER_TIMEOUT: "provider_timeout",
});

export const RENDER_MODE = Object.freeze({
  FULL_REPORT: "full_report",
  WARNING_REPORT: "warning_report",
  SOURCE_REQUIRED_REPORT: "source_required_report",
  BLOCKED_REPORT: "blocked_report",
  PROVIDER_ERROR_CARD: "provider_error_card",
  PROVIDER_TIMEOUT_CARD: "provider_timeout_card",
  DATA_REFRESHED_REGENERATE_REQUIRED_CARD: "data_refreshed_regenerate_required_card",
  USER_INPUT_REQUIRED_CARD: "user_input_required_card",
});

export const MISSING_VALUE_MARKERS = Object.freeze([
  VALIDATOR_STATUS.SOURCE_REQUIRED,
  VALIDATOR_STATUS.USER_INPUT_REQUIRED,
  "no_quantified_data",
  VALIDATOR_STATUS.REALTIME_VERIFICATION_REQUIRED,
  "not_applicable",
]);

export const SOURCE_TIERS = Object.freeze({
  L1_GOVERNMENT_REGULATION: "L1_government_regulation",
  L2_STANDARD_INDUSTRY_BODY: "L2_standard_industry_body",
  L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL: "L3_customer_cloud_operator_official",
  L4_VENDOR_OFFICIAL: "L4_vendor_official",
  L5_LOCAL_KB: "L5_local_kb",
  L6_UNCORROBORATED_REFERENCE: "L6_uncorroborated_reference",
});

export const CONSUMER_MODULES = Object.freeze({
  ASK_POWER_INSIGHT: "ask_power_insight",
  COMPANY_INTELLIGENCE: "company_intelligence",
  MARKET: "market",
  PRODUCT: "product",
  TECHNOLOGY: "technology",
  DASHBOARD: "dashboard",
});

export const CLAIM_TYPES = Object.freeze({
  REGULATION_COMPLIANCE: "regulation_compliance",
  STANDARD_CERTIFICATION: "standard_certification",
  CUSTOMER_DEPLOYMENT: "customer_deployment",
  VENDOR_PRODUCT_PARAMETER: "vendor_product_parameter",
  CDU_ARCHITECTURE_RULE: "cdu_architecture_rule",
  AIDC_TREND: "aidc_trend",
  LOCAL_PLANNING_ASSUMPTION: "local_planning_assumption",
  TAM: "tam",
  ROI: "roi",
  MARKET_SHARE: "market_share",
  CERTIFICATION: "certification",
  LAUNCH_DATE: "launch_date",
  TECHNICAL_PARAMETER: "technical_parameter",
  NAMED_CUSTOMER: "named_customer",
  COMPANY_REVENUE: "company_revenue",
  ANNUAL_REPORT_METRIC: "annual_report_metric",
  QUARTERLY_REPORT_METRIC: "quarterly_report_metric",
  PARTNERSHIP_CUSTOMER: "partnership_customer",
  PRODUCT_LAUNCH: "product_launch",
  EXECUTIVE_CHANGE: "executive_change",
  SUPPLIER_UPDATE: "supplier_update",
  ROADMAP_STATEMENT: "roadmap_statement",
  WHITE_PAPER: "white_paper",
  PRODUCT_MANUAL: "product_manual",
  PRESS_RELEASE: "press_release",
  INDUSTRY_REPORT: "industry_report",
  SST_COMMERCIALIZATION: "sst_commercialization",
});

export const CLAIM_TYPE_SOURCE_PRIORITY = Object.freeze({
  [CLAIM_TYPES.REGULATION_COMPLIANCE]: [
    SOURCE_TIERS.L1_GOVERNMENT_REGULATION,
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.STANDARD_CERTIFICATION]: [
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L1_GOVERNMENT_REGULATION,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.CERTIFICATION]: [
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L1_GOVERNMENT_REGULATION,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.CUSTOMER_DEPLOYMENT]: [
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
  ],
  [CLAIM_TYPES.NAMED_CUSTOMER]: [
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.PARTNERSHIP_CUSTOMER]: [
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.VENDOR_PRODUCT_PARAMETER]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.TECHNICAL_PARAMETER]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.CDU_ARCHITECTURE_RULE]: [
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.AIDC_TREND]: [
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.LOCAL_PLANNING_ASSUMPTION]: [
    SOURCE_TIERS.L5_LOCAL_KB,
  ],
  [CLAIM_TYPES.ANNUAL_REPORT_METRIC]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.QUARTERLY_REPORT_METRIC]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.COMPANY_REVENUE]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.PRODUCT_LAUNCH]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.EXECUTIVE_CHANGE]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.SUPPLIER_UPDATE]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.ROADMAP_STATEMENT]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.WHITE_PAPER]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.PRODUCT_MANUAL]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.PRESS_RELEASE]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
  [CLAIM_TYPES.INDUSTRY_REPORT]: [
    SOURCE_TIERS.L2_STANDARD_INDUSTRY_BODY,
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
  ],
  [CLAIM_TYPES.SST_COMMERCIALIZATION]: [
    SOURCE_TIERS.L4_VENDOR_OFFICIAL,
    SOURCE_TIERS.L3_CUSTOMER_CLOUD_OPERATOR_OFFICIAL,
  ],
});

export const GENERIC_FILLER_TERMS = Object.freeze([
  "平台化和规模交付",
  "加强可靠性",
  "全面优化",
  "持续提升",
  "深化布局",
  "打造生态",
  "赋能客户",
  "降本增效",
  "推动高质量发展",
  "端到端能力全面升级",
]);

const BLOCKED_STATUS_SET = new Set([
  VALIDATOR_STATUS.BLOCKED_SOURCE_REQUIRED,
  VALIDATOR_STATUS.BLOCKED_OBJECT_MISMATCH,
  VALIDATOR_STATUS.BLOCKED_SCHEMA_ERROR,
  VALIDATOR_STATUS.BLOCKED_POLICY_VIOLATION,
  VALIDATOR_STATUS.BLOCKED_GENERIC_FILLER,
  VALIDATOR_STATUS.BLOCKED_PAGE_CONTEXT_MISSING,
  VALIDATOR_STATUS.BLOCKED_PAGE_CONTEXT_MISMATCH,
  VALIDATOR_STATUS.BLOCKED_FRESHNESS_UNVERIFIED,
]);

export const mapStatusToRenderMode = (status) => {
  switch (status) {
    case VALIDATOR_STATUS.PASS:
      return RENDER_MODE.FULL_REPORT;
    case VALIDATOR_STATUS.PASS_WITH_WARNINGS:
      return RENDER_MODE.WARNING_REPORT;
    case VALIDATOR_STATUS.BLOCKED_SOURCE_REQUIRED:
    case VALIDATOR_STATUS.SOURCE_REQUIRED:
      return RENDER_MODE.SOURCE_REQUIRED_REPORT;
    case VALIDATOR_STATUS.USER_INPUT_REQUIRED:
      return RENDER_MODE.USER_INPUT_REQUIRED_CARD;
    case VALIDATOR_STATUS.PROVIDER_ERROR:
      return RENDER_MODE.PROVIDER_ERROR_CARD;
    case VALIDATOR_STATUS.PROVIDER_TIMEOUT:
      return RENDER_MODE.PROVIDER_TIMEOUT_CARD;
    case VALIDATOR_STATUS.REALTIME_VERIFICATION_REQUIRED:
      return RENDER_MODE.DATA_REFRESHED_REGENERATE_REQUIRED_CARD;
    default:
      return RENDER_MODE.BLOCKED_REPORT;
  }
};

export const isBlockedStatus = (status) => BLOCKED_STATUS_SET.has(status);

export const isMissingValueMarker = (value) => MISSING_VALUE_MARKERS.includes(value);

